@api = http://localhost:3000/matches


# Get all matches from user
GET {{api}}/user/2
###

# Create a new match
POST {{api}}
Content-Type: application/json

{
   "pitchId": 1,
   "userId": 1,
   "matchDate": "2024-09-04 10:30"
}
###

# Cancel a match
POST {{api}}/cancel
Content-Type: application/json

{
   "matchId": 37
}
###

# Get all participants from a match
GET {{api}}/participants/29
###

# Get match deatils from match id
GET {{api}}/6
###

# Get all matches from user and status
GET {{api}}/status/2/scheduled
###

# Add a participant to a match
POST {{api}}/participants
Content-Type: application/json

{
   "matchId": 29,
   "userId": 9
}
###

# Remove a participant from a match
DELETE {{api}}/participants
Content-Type: application/json

{
   "matchId": 4,
   "userId": 2
}
###

# Get all invitations from a match
GET {{api}}/invitations/35
###

# Get all match invitations for a user by status
GET {{api}}/invitations/2/pending
###

# Add an invitation for user 3 to match 35 from user 1
POST {{api}}/invitations
Content-Type: application/json

{
   "matchId": 59,
   "userId": 2,
   "senderId": 1
}
###

# Delete an invitation 
DELETE {{api}}/invitations/35/3
###

# Accept an invitation
PUT {{api}}/invitations/accept
Content-Type: application/json

{
   "matchId": 41,
   "userId": 3
}
###

# Reject an invitation
PUT {{api}}/invitations/reject
Content-Type: application/json

{
   "matchId": 35,
   "userId": 3
}
###

# Update match status
PUT {{api}}/newstatus/
Content-Type: application/json

{
   "matchId": 55,
   "status": "completed"
}
###

# Update match status
PUT {{api}}/newstatus/
Content-Type: application/json

{
   "matchId": 55,
   "status": "scheduled"
}
###

# Get matches by access type
GET {{api}}/access_type/public
###

# Get private matches
GET {{api}}/access_type/private
###

# Change access type of a match
PUT {{api}}/change_access_type
Content-Type: application/json

{
    "matchId": 72,
    "accessType": "public"
}
###

# Set a new visitor team for a match
PUT {{api}}/setLocalTeam
Content-Type: application/json

{
   "matchId": 6,
   "teamId": 217
}
###

# Set a new visitor team for a match
PUT {{api}}/setVisitorTeam
Content-Type: application/json

{
   "matchId": 6,
   "teamId": 217
}
###

# Remove all players from a match
DELETE {{api}}/6/players
###

# Add players from a custom team to a match
POST {{api}}/6/teams/217/players
###

# Set goals for a participant
PUT {{api}}/participants/goals
Content-Type: application/json

{
   "matchId": 6,
   "userId": 7,
   "goals": 3
}
###

# Set assists for a participant
PUT {{api}}/participants/assists
Content-Type: application/json

{
   "matchId": 6,
   "userId": 7,
   "assists": 2
}
###

# Set match score for teams A and B
PUT {{api}}/goals
Content-Type: application/json

{
   "matchId": 4,
   "teamAScore": 2,
   "teamBScore": 1
}
###