@api = http://localhost:3000/matches


# Get all matches from user
GET {{api}}/user/2
###

# Create a new match
POST {{api}}
Content-Type: application/json

{
   "pitchId": 1,
   "userId": 1,
   "matchDate": "2024-09-04 10:30"
}
###

# Cancel a match
POST {{api}}/cancel
Content-Type: application/json

{
   "matchId": 4
}
###

# Get all participants from a match
GET {{api}}/participants/1
###

# Get match by id
GET {{api}}/37
###

# # Add a participant to a match
# POST {{api}}/participants
# Content-Type: application/json

# {
#    "matchId": 1,
#    "userId": 1
# }
# ###