@api = http://localhost:3000/users


# Get Users
GET {{api}}
###

# Get User by ID
GET {{api}}/3
###

# Get User by Username
GET {{api}}/username/root
###

# Get User by Email
GET {{api}}/email/root@gmail.com
###

# Get number of Users
GET {{api}}/count
###

# Sign Up User
POST {{api}}/signup
Content-Type: application/json

{
    "name": "Prueba",
    "email": "prueba@gmail.com",
    "username": "prueba",
    "password": "root"
}
###

# Delete a user
DELETE {{api}}/4
###

# Update a user
PUT {{api}}/2
Content-Type: application/json

{
    "name": "Antonio",
    "email": "tone@gmail.com",
    "username": "tone",
    "password": "tone"    
}
###

# Login User
POST {{api}}/login
Content-Type: application/json

{
    "username": "root",
    "password": "root"
}
###

# Get Friends
GET {{api}}/friends/3
###

# Get isFriend
POST {{api}}/friends
Content-Type: application/json

{
    "userId": 1,
    "friendId": 3
}
###

# Get Friend Requests
GET {{api}}/friend_requests/3
###

# Send Friend Request
POST {{api}}/friend_requests
Content-Type: application/json

{
  "sender_id": 1,
  "receiver_id": 3
}
###

# Accept Friend Request
PUT {{api}}/friend_requests/accept
Content-Type: application/json

{
    "requestId": 203
}
###

# Get Friend Request status
POST {{api}}/friend_requests/status/
Content-Type: application/json

{
    "sender_id": 3,
    "receiver_id": 1
}
###

# Remove Friend Request
DELETE {{api}}/friend_requests/3/1
###

# Delete Friend
DELETE {{api}}/remove_friend/1/3
###

# Validate Token
GET {{api}}/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5NzkzMTE0LCJleHAiOjE3MTk3OTMxMTV9.ZdvJfjQ9UOghzetFNVLAeFPnTQNzJHh5Y_5iVbLUk0o
###

# Validate Token
###
POST {{api}}/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5ODc1MjQ4LCJleHAiOjE3MTk5NjE2NDh9.Qv_SNVQFPPtc9hv7FYO5wTuCsKNvQgFOk5xBDWXFhgs"
}
###

# Update a user photo
PUT {{api}}/1/update_photo
Content-Type: application/json

{
    "photoUrl": "https://this-person-does-not-exist.com/img/avatar-gen4fa732bb26c3e8561e4c8fd0c62a0e4a.jpg"
}
###

# Update User Role
PUT {{api}}/2/update_role
Content-Type: application/json

{
    "role_id": 2
}
###

# Get last game played
GET {{api}}/1/completed-match
###

# Create a new publication
POST {{api}}/publications
Content-Type: application/json

{
    "text": "This is a sample publication from the user 5",
    "likes": 10,
    "user_id": 5
}
###

# Delete a publication by ID
DELETE {{api}}/publications/1
###

# Get publications from friends
GET {{api}}/publications/friends/2
###

# Get the number of likes of a publication
GET {{api}}/publications/2/likes
###

# Add a like to a publication
POST {{api}}/publications/2/like
###

# Remove a like from a publication
DELETE {{api}}/publications/2/like
###

# Update user experience points
PUT {{api}}/7/exp
###

# Get user experience points
GET {{api}}/3/exp
###

